### ISSUE TITLE
Running problems

### ISSUE THREAD

**Issue by fengjiufa** [yahoochen97/CNNForecasting#1]
Hello！When I run your code, CNNDATAidx.csv does not have this data. When I changed it to CNNData.csv, I also changed pollsteridx to pollsteridx, but it still reported an error, showing
“Error using a real integer logical value character vector or character vector cell array whose subscript must be positive for getRaceCandidateData (line 4) table variable。”
Can you help me？Thanks~

**Comment by yahoochen97** [comment]
Hi,

This repo is no longer maintained. See this published capsule for latest version. 
https://codeocean.com/capsule/8106129/tree/v1

Yehu
